### ISSUE TITLE
bug on mouseup on a bar

### ISSUE THREAD

**Issue by checksummaster** [soanvig/mm-jsr#107]
If you drag a JSR.bar and release the mouse keeping the cursor on the bar, the nearest point move (look like the mouse up on a bar does the same job as a mouse up on a point).

If you release the mouse anywhere but on the bar, it works well.

You can reproduce on https://soanvig.github.io/mm-jsr/#demo (the first slider).

**Comment by soanvig** [comment]
Confirmed, thank You :-)

**Comment by soanvig** [comment]
Release in v2.1.3
